<?php
namespace lib;

use Illuminate\Config\FileLoader;

class Loader extends FileLoader
{
    public function load($environment, $group, $namespace = null)
    {
//        if ($environment == 'production') {
//            $namespace = $environment;
//        }
//        $this->addNamespace($namespace, $this->defaultPath);
//        return parent::load($environment, $group, $namespace); // TODO: Change the autogenerated stub
        $path = app('path.base') . "/production";
        $this->addNamespace('production', $path);
        $default = parent::load($environment, $group, $namespace); // TODO: Change the autogenerated stub
        $file = $path . "/{$group}.php";

        if ($this->files->exists($file)) {
            return $this->mergeEnvironment($default, $file);
        } else {
            return $default;
        }
    }
}